// <auto-generated />
namespace VirtoCommerce.InventoryModule.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddSkuIndex : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSkuIndex));
        
        string IMigrationMetadata.Id
        {
            get { return "201705121220219_AddSkuIndex"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
